=== hmcts/cpp-context-notification-notify/notificationnotify-command/notificationnotify-command-handler/src/raml/json/schema/notificationnotify.command.send-email-notification.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/json/schemas/domains/notificationnotify/notificationnotify.command.send-email-notification.json",

  "type": "object",
  "properties": {
    "notificationId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "templateId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "sendToAddress": {
      "type": "string"
    },
    "replyToAddress": {
      "type": "string",
      "format": "email"
    },
    "replyToAddressId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "materialUrl": {
      "type": "string"
    },
    "fileId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "personalisation": {
      "type": "object",
      "properties": {
      },
      "additionalProperties": true
    },
    "clientContext" : {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "notificationId",
    "templateId",
    "sendToAddress"
  ]
}

=== hmcts/cpp-context-notification-notify/notificationnotify-domain/notificationnotify-domain-aggregate/src/test/resources/json/emailWithFileId.json
{
  "notificationId": "5c5a1d30-0414-11e7-93ae-92361f002671",
  "templateId": "384416a9-ef20-4500-a9c1-f64b87b424a0",
  "sendToAddress": "fred@bloggs.com",
  "replyToAddress": "noreply@moj.gov.uk",
  "replyToAddressId": "9f476d4f-4069-444a-a511-905dcbb66910",
  "fileId": "114416a9-ef20-4500-a9c1-f64b87b424a1",
  "personalisation": {
    "referenceNumber": "13566",
    "lastName": "Bloggs",
    "firstName": "Fred",
    "subjectLine":"Subject Line"
  },
  "clientContext": "correspondence"
}

=== hmcts/cpp-context-notification-notify/notificationnotify-domain/notificationnotify-domain-aggregate/src/test/resources/json/emailWithMaterialUrl.json
{
  "notificationId": "5c5a1d30-0414-11e7-93ae-92361f002671",
  "templateId": "384416a9-ef20-4500-a9c1-f64b87b424a0",
  "sendToAddress": "fred@bloggs.com",
  "replyToAddress": "noreply@moj.gov.uk",
  "replyToAddressId": "9f476d4f-4069-444a-a511-905dcbb66910",
  "materialUrl": "http://localhost:8080/material-query-api/query/api/rest/material/b439f425-e894-4a2c-aeb8-ed172565720f",
  "personalisation": {
    "referenceNumber": "13566",
    "lastName": "Bloggs",
    "firstName": "Fred",
    "subjectLine":"Subject Line"
  },
  "clientContext": "correspondence"
}
