=== hmcts/cpp-context-notification-notify/notificationnotify-command/notificationnotify-command-api/src/raml/json/schema/notificationnotify.email.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/json/schemas/domains/notificationnotify/notificationnotify.send-email-notification.json",
  "type": "object",
  "properties": {
    "templateId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "sendToAddress": {
      "type": "string"
    },
    "replyToAddress": {
      "type": "string",
      "format": "email"
    },
    "replyToAddressId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "materialUrl": {
      "type": "string"
    },
    "fileId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "personalisation": {
      "type": "object",
      "properties": {
      },
      "additionalProperties": true
    },
    "clientContext" : {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "templateId",
    "sendToAddress"
  ]
}

=== hmcts/cpp-context-notification-notify/notificationnotify-integration-test/src/test/resources/raml/notify.command-api.email-notification.json
{
  "templateId": "384416a9-ef20-4500-a9c1-f64b87b424a0",
  "sendToAddress": "fred@bloggs.com",
  "replyToAddress": "noreply@moj.gov.uk",
  "replyToAddressId": "9f476d4f-4069-444a-a511-905dcbb66910",
  "personalisation": {
    "firstName": "Fred",
    "lastName": "Bloggs",
    "referenceNumber": "13566"
  }
}
