=== hmcts/cpp-context-notification-notify/notificationnotify-azure/notificationnotify-azure-functions/src/main/resources/json/schema/email-details.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "id": "http://justice.gov.uk/json/schemas/domains/notificationnotify/paas/email-details.json",
    "properties": {
        "attachment": {
            "properties": {
                "content": {
                    "contentEncoding": "base64",
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                }
            }
        },
        "emailAddress": {
            "type": "string"
        },
        "personalisation": {
            "additionalProperties": true,
            "properties": {},
            "type": "object"
        },
        "reference": {
            "type": "string"
        },
        "replyToAddressId": {
            "pattern": "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
            "type": "string"
        },
        "templateId": {
            "pattern": "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
            "type": "string"
        }
    },
    "required": [
        "templateId",
        "emailAddress"
    ],
    "type": "object"
}

=== hmcts/cpp-context-notification-notify/notificationnotify-azure/notificationnotify-azure-functions/src/test/resources/json/request.json
{
    "reference": "52f98ee8-0bb2-4859-bd95-17178fd752d0",
    "emailAddress": "Drive.course@aquarius.cjsm.net",
    "attachment": {
        "filename": "Notice of Reduction in Disqualification_20210415115611.pdf",
        "content": "JVBERi0xLjQKJcOkw7zDtsOfCjIgMCBvYmoKPDwvTGVuZ3RoIDMgMCBSL0ZpbHRlci9GbGF0ZURlY29kZT4+CnN0cmVhbQp4nL1ZS4/jNgy+51f4XCCpRD1sA0EAx3EOvS0QoIeit24L9FCge+nfr0S9aJuWMzOZwQJejyNT4sfXR1qcZPPf4d9GNMLdmd6coOm0PHXNj++HX39q/gm/uX8//jpcHwcNJ9u0nTyp5vFH8/NdNrJrHn/+dhZSgFBCCyOsaN19dzmas7vr3d+DuLrn/lcQo3um8Xpz/0/iLq5SSOnuO/+2FGnd5ffHL4fpcfjGHkEbcgQIR7hdjnCW4nKUZ6EucBYWb1t/C3jb+dvWn0yCu5VKDBcb10m1tSPY/qTZLaV2r0sTtzFOopVtFNadhcYDSX/FU7jl/rcOr/hqX9cS2vWWA4oDf+5r2ErsnZwTc/XbI1ZyjECNeKWIRKxuF1OUMUUj/9vkFI1y7vg+rnOGVQjw2hwTiGyW9ygjFW8GkF4AQLm6LbZE9VuiQEVXueZzg87nBXMBmxW5HNuoWYDCQxrfJlDSB6jz9DVwoQfZnnHagcSJN1+OEx+xvbe1LdGSPIG6iIvxupHYbdHhEUuwXnIIVxIS0HozdsWA8cd6kNh27d1B9koNd3zrreKFCqIPWrm/ACSjYspAV8dlMOwqzBwCrglKgYdozykpeunEs4LLDiFzBIskp6kqbvpPUNwKl8TC0viCKi4yuWV1HJgzucB0Zg0bRt+nQQG3EEEbcpU023L960HIhFERM1OIKUPyf0hhNLKn8OvO7lpYVxHZ3VUM2biLLYF7KyE0uYqmYupsywpd4niMLr5/logwV4ZI5jExu8ics4OV73mP4IJbcIPa2ESJi/SejNsoFD+WIN2Va7UjFRtyMbEmFBQUq2FlVcohWg0Epr69JAPccgaY84mjWRAKOCsdraxSZNetyJXkbkUmBFbp+8xtVc4hDq/0AqQEWsVJ9M6ZF25sKTY56J+hRIoV6MqblXhWZaqnMb1cvfweq8U6FurzLKFS/lfsFyIj3GJI5pdSNM7sPOZiC4Oyz2PDqUcsTK+AjxMrLOmgK+Wwq0PZqtdDOcRIt5GmZN5HUB2LZyI6z3FptTiwTOAgIPQC+Awv2oelAyY+hLi6Cosxr4AlqBprYYzyEQGJCfBeEtas/pS6WWjTx6FjlHIx59sZx93cvhjR0sa6iLUXCMeSJceCCuw9ZFmt6tnDqHYDTb7lCo4D9/AHAgOeAiZ0CK12yJDS7ECeiBzniCX1AZWdF1WPjQVtcWxDOJed+zXRYtixBAMIIblP5nC9jv2qOsK4K+vTsZPwXkd2W9OBrjAQQ023JCWxq2lpP0jWVNHR7EFlMbmc6E6EDG8STFRfd+0Xq+/5XUoN0X5m/kIJcFSMxWvXnTSrGgFs1nriVXV7YGmmBNWav0xmaee3kcVUXxrfemdnPS8pHCV1drvTD82wiyBaDYFhSHsxXYQdMKRSmwVbmdcfdyi9QCI7dctwB/Eepa6oaDjLtaqMcnRALm1hY+Yx6HaUvNCh0ZWQjjFbg66gFWugIVZSGiU5Q8Fi0avUcVAMpcECE/NXV3K/jscDumsVH4bC7Nu0flxeZBz7ESKnRjGpeouhmKqLPWcAbsoQBvKkphwcocC15W+zTHxSLWwu+9AUqSG+Qg1Jyilt70gxLcyEFrP0oKollzCocwH1p+WYEAsdKd1HMztLHHGVfEzHiGrZrpJYIKM46u7P8a2qusAU8GFZBuhgTiq4l/ZQlcEy/p1Ur9aHMOQK5AzTohrj/zc1hl3ULelpl1HtofI5IBA4XFjVUDKNwXIUTgEnBLWduzDJmjBkTjYSQscV06L7lGdLZk5/UpHIM0Cv2H0ntDkSDJkYknIfiBc9GiRDph7/mGJmWhCHxTzpbcQhRMO4WEaydsBai3mQ2lkDTrL5bCZMEWyJghMt6Tt8gwt2LYNMlUXYp0hPwAZm2cCUOSal9fUzcf564ybSNC5ooBRg6PSyNG1HYLs2sxwaxgyynI6/bxqgG//B4au7trhzy45ZNgdb2IpicKS0HFPDRttmn+jakklIm7tykjT/5pqx/W4DTLUXw3os0yglP3j+c1zcBVhGmp2nJBBbCh2fQPJXs51egnpYd35LPwGSyZEfacCCWNmxY4DPw0DNUuEiGZk90OiaHcAkxxff24BFkZqdQL0pn5W5XGYeOJuzZTSXPsy+JFU5rvO6weX2hC5uJj6e8DmAdP4gUhkD5zyDPfuMcs7nwMtxnSdgb0C0Y3L/6yfB8cMCk+0XHzKzTisiuFGy5y84/7gvjRBDfx7Nq9hMXrn/UdWR17YBseqYP/OTai829pwCFbzPXGJDigFYy/BWfPzNL+/4TbmPTFtbav+BlNlU502/Nf8Ddu2yHwplbmRzdHJlYW0KZW5kb2JqCgozIDAgb2JqCjE3NDUKZW5kb2JqCgo1IDAgb2JqCjw8L0xlbmd0aCA2IDAgUi9GaWx0ZXIvRmxhdGVEZWNvZGU+PgpzdHJlYW0KeJzNVLtqxDAQ7P0VqgN2dlcP22AEtmMX6Q4MKUK6PCBFINfk96OV5Mdh+5ziinAgdGtpZnZ2tZCh+Em+BQhwO13qjEShMCvE+S15uhNf4Zv7nT+SZkjIlJkSeYGZFMOruO9RIInh/blCA701FTQ2xQrBrxKU1TEEHeQ2df8eOFTalCpFlipZS21fhsekG5LTNpuWKzZAhxJYqAbjCXKHBuS3BW8DnbbFGG2iqG5xIWBAPa8o+YaJmqNqZD6XjVMNLac5IvC38kC/LNduKQdCudffTmKk8pYxSQdySseRpxTz88a5sJmVXyfHdan+lXnqun5T5iv9UjGJx0PpMhiRmZ97kNTcg3TgjzHr4tzOH1/geCBW1APpGAvOmQOJWm9YQDjRkAcjth6bAyxa23mzdMOWaodlxvrMrfvXZjl4TQY3pgHPlPHpYBsgZb90etI7USo5d4kbXeGQWY4uVh5nVwSjJjxOqkOgjfXjVe7pVpTlgni+Xqp2YDpcBu9yzivb7L3kZgmNHDJwtoZu6uYitLuUJexwdr442C+E53sommiNwS92+Nw+XmyTxu65aKc9SqVdja+SnsQv6PJwYAplbmRzdHJlYW0KZW5kb2JqCgo2IDAgb2JqCjQ0NQplbmRvYmoKCjggMCBvYmoKPDwvTGVuZ3RoIDkgMCBSL0ZpbHRlci9GbGF0ZURlY29kZS9MZW5ndGgxIDI3MzkyPj4Kc3RyZWFtCnic1bwLeFPHtSg8a2ZvSVuyrC3Zki2/JFl+S5Y2lm38QPYGbCHHPAzYYBuMbfCTh21sQ3gkwSRAwJDgpJSEQANtSRryQiQkIU1S3DYnadqk4aRpenLSFm6b5rRNKJw2zW0abN+ZLdkYkube77//9/3fL1va81izZs2amfWYxx7s39SOotAQIkhes6G1L+BcNgch9CZCYFqzedB+Zd5DqTR8CSFs6ejr3JDl++AvCJF/IKTmO9dv7ViZc3IUIR0tsiTU1d7a5v7J9hKEmkI0obCLJnxj/E41jf+RxtO6Ngxu2Zv0Bw6hVVEUp7i+d03ruXvvOIBQcxLNH97QuqWvQ7WU0PhjNG7vad3QXvDf8CGN/wQhjdzXOzB4GOVMINSlYfl9/e19hat+UkbjWZS+X9I0oH/sw/CrWBwTjlepNYJWF6WPNohGU0ys2RIXb01ITEpOsdkdqc609IzMrOwclzvX45Vm5PnyCwpnFhWXlM7yl5XLs+fMRf+//vBv8m+i2/mdyIy2Kr83fLgSFItuRWjiExa7/ju+/P9dKjThx1n0CjqNTtyQtRfdQX+fvCHtPPoxekIJHUX3fA3aF9HjkdAhdATd/S/h1qK7KJ6TtP7rnxaauhU9SGs+h75HB0oq+Git6yK5H6A3vhoV/A94A92PHqOQ96MX6O9ROvK247+i+/ES1IN/RXaiO9E+2sbj0I0OUvgWdBJWoFU0NfxZhdpR701Ih9EIegRto7Nw6sPvnPgb0l/7HqV8H8VzGHWjjdNKPAafswexUdqfRs8paTsnM9VBshY/j/HYN2jkPtRJv63wPqXzHjIbVfBGOIWQXNlQX1e7dMnimkULF8yvvqUqOC9QWTF3zmy5vMw/q7SkuGhmYcEMyevJdWdlZqSnOVMdtvhYo2iI1uu0gkat4jmCAbkrnYEWeyijJcRlOIPBXBZ3ttKE1mkJLSE7TQrcCBOytyhg9hshZQrZcROkHIaUpyBBtM9Cs3Ld9kqnPfRWhdN+DhoX19PwPRXOBnvoshJeoIS5DCWipxGHg5awV8Z3VdhD0GKvDAU2dw1XtlRQfGd02rnOue3aXDc6o9XRoI6GQlnOvjOQVQZKAGdVlpzBSKNn1YZIemVrW6hmcX1lRaLD0ZDrrgpFOyuULDRXQRlSzQ2pFZT2bkY62m8/4x4dPnBORKtbXFFtzrbWlfUh0krLDpPK4eG7Q0ZXKNtZEcre9mE8bXl7yO2sqAy5GNbqJVP1VF+vEkJ8uui0D/8d0eY4L39yY0prJEWVLv4dsWCAsnd4OOC0B4ZbhlvPTQytdtpF5/CZqKjhvkrKYVRTT0udm/j+/sRQ4EBDSGzpgpJIYwNLqkMxi1fUh3B6wN7VSlPof7nTUZToMDZMwtT8q2xEGUHZQXnqcLCG7z8no9U0EhpaXB+O29HqxGeQ7HU1hHALyxmdzDHXsZyhyZyp4i1O2pvVS+uHQ1x6VZuzkvJ4f2toaDUdT2tZVzjFUPRniQ7nsMloL/Y2KLB2SlVVW7c9xGdQttBS0wvQkcKKDItKJPqz8ONyIq0gw2iyFzspGoan0lnZEvnf3BVPEdhz3aGgK9z1tfUhuYIG5NZIH1Wekby0RGsL7aLuCqX7Ql5nXyjWOWeqPxlZld1L65UikWKh2Lkh1LImUirkraxgNdsrh1sqwiQwXM7F9S8i38SlM/n2xGd9KB81VDBgy1w6rjIqh+vbOkK2lsQ2OtM67PWJjpDcQDu4wVnf3sAGGuVQ9iVanUOpMYTn1tZXL3VWL26sL4oQEs5g6Lj0ypvQOOsTw2jokAtp0jX2epxIGiigSBPsARpwzplFf0PqdA39ipThSiobqnNm2eshEU1CUzJC2fbK9ooIHIvfgJRnw2lucBKbikUpnrnBREeDI/zJdWOabY9UTEtoGFODk1kknUoCmoYpGiWJ8TKejXl7vbPd2eDssofkmnrWNsYehcsRZig8j/RV7Q2xacyibEIOmj0ZYcwMBVyJ05kbmqfEp6LBm7KrJrPtwxpn9dJhhtwZQYgo5VUhxIawXGRMVGY/m8/OQCudxHRGK/N5+Iwss7ncxabtsLOqbdi5tH6WAk0lyO2J21hdJlQN1bVzct1UmM0544S9i8/IsHdpY/2LIjWp9tbWP4MBz22Z03AmjebVv2inukJJxSyVJbKInUUYpiU0olHgE1+UERpScjklQYmvOQdISdNMpgFacw6H08TJNEzTuHCarKSxD+2l+C7KYyq/K+1trH9ua+gabmlgYxxZKEfoP4TAWUa54yw7A1gVFdI62+eEdM45LL2cpZeH01UsXU1HBlgg171tWKx0/j0+lylLjCroTxtfRy1gNfKcAeSd9Yya01zOO6Pifz3rGYJpEJ0hLJlnyc+oVcK1Wc8AS/cZHcZ0h9FRge3jafDgeBdf988nKri3mKFAbQTE26nNFYNefRFpJy7JmVGuYKE2oMXITkPZqBhVIaITkx1Bnd2UFDyse1SHs3UA5yauPksT6fOSXEAzHoLHqR2bARCzElWIteIhkVwSASNREmWxTxwVL4gqUTaDbB41XzBfMnPmcxOjshhtDGrVK5FG1MgaotaAkpjsChpBIDqZBnRIY0LlPp+LfcG7qulynqtpo7epuWmj7/IMCdGAy9VEv9DkanI5wBKXAmaj0+iDjEwPFBh9Rq5kLBoTTB7/Lf4nIZh7kgvNkLJXOK/V8zu/CM6YkbMmlxz7544wn5dNfMIlcwtRNEpFg3LpVvs+Ox5M2pWEN1v2WPBW0z4TPhz1aBTmomKjsE5IFLCOT+TpYIrFWI3mySMGMKQNSWmQxloSm+IMXkwD6zybBjSxNVoxpYZYUPnl8svgbbrc5NqYIP66KYE2Y1XT5AdE7Ez14ALRkZeC1fkeGovG5tgU7Msrw1zyP/+y8Znts+EPd7ywqeiVzOr1FZW9C7PdC7rLKvsW5uCU8Q/H/1xx4BcHsRQ48M6BO06uzsxec3L7HY+szspc/Sjrb9vEVZzDu5EFbZeXZ0VDd/TW6H3RJEsP3fqt+n16sp8Dzi7og+u527hjlFccjUUFey07LNgSpbcQMSBoDvKAeJGOG5nn1PxQPBhUNVHlWtAKhphIA99q8l3OgybaXxt9vstxed4m2leuJqBdtbFpY3o0OFMLjM4C30yf2Wd2GmMtvrzCmTgnu67oP27fVbDlJz/xlSfMSNbo9H/H79z117/eNVa3sFyjCvfRPtoQP/UY2FwYkPVEHaBOgshJHNFwjOs55vggx2mECQEuCXBRgJAwKuDjAvQJQwK2CYAEuKpkCAzcmJoeXCQATecNnBktpc4ZbUA5NG10bdzYH/kYTcVe1yrWqBlSTIHPTOjA2nf27Fne/uST/7zElXzxmmJ4o+UTn5Cf0vGTiTbJi7eKsDUO1qTDGgL2gM2mCZygdQrZaJ4tBmKcNQk2+w77QftFO2e3J4h2TZ9mSHNBc0nDs/nQokRHaYJao+Froi22bGiilPm8TRvL6Y+ojCGj73bvxniaSAeRMnyUkVI4My6aKMMov4zz0YEUp/YAG0gQkyh3L2jZaXhemNV5qHXHM715abPrO/tLVtzbKetfjO7vXtApJ+LUpmMby7rWR829bVXxsgfe2rLhe7fX+eLylm+uiG5c6+s8Fu4H2lYunrY1CaWjdbKn0bnWiRtT1qbgOtJOJVKVICTOk23JMJIMyZlD6bTVRjBKmaOZFzJJJuN8DJ0etG2oJj2dt9dYRNZKZXZQZl82FnvBRSf65Tw2STYmXM5T2ohuaiM25pdh1sRkyAy3UQ2xzqr+mk33WB82+juOrL/6xfxdoba9L/R6v28YuTt3TW0JB/+z7mBn8apgbu6KKi+kQMKDv9hVWn/0nW3xw098K/mWHauVvkymjZzF/xQlom/LOqKN0fq0c7WcXstE3lpNVDDBIEK0aBUhwCMMJmxL9iYvSm5O3pF8MPl4stqQXE6Dp5PPJ19MvpKsLm2mIRzOI8nysrZgspzpDtqTpeSWZHJaASJyMhgoFhxTE0UdpxqrygBmVF5Ohx0VGbR7N7pcG/vpnPIqQzGPPdi8WtUEVOTR6VSgMMMSZw6zIhl8Zug+++CDltKOxfbKBGOuKcuXrPsFeeFaFXnhrm2l7dUulWof4S3ZszJb76J9yvRBF9UHRpSC3pHLTulhOPah2MdjyaFk2JS8Oxk/jeBbCG5DBxC+BTVS/5SQEwD9cCfcDwSvAZABfADpAEQ8N9EnLzdW9YlD4ohIasU2Ec+hOsEp+kQMomg1Nep0CBklo2xsMY4YTxhVRtk+Yj9hJ1bSyKa0zBE1J+Jmr7XZ2ms9aOWsVhTfzBMOUZ2Qp4wTOj7CWqHJ2+Sjw8ZUbKQsoVqB6gT2w0LKE7EfBzgoo5hoNceykUKYgKW6kcnWA+P3j1edxw9sefGOOZm1d66AkX+4a7fMHy+Ft5ZsWZCOq8Ze4HfO7Dq8au6d6xeKY98mn8irym1j/8gOrp7SHeQKlUs25GPStS61PRU35q3Nw8VQBVhRqgJn5bZy+zhOpbaoN6v3qLmYgJyDDpqumLCpYMg+z6YCVV/BSAG2FcBEAYwWXCrAVrMJ6bw1GhGlh6VrHvunAqppI5sfbHrk5SUoylD5KNIVG6kGscT58j2Qz7QgnTNxTg8pgIgqKYioFlKQ98i2t34I924/mYcBzgLG8CSmenLsP5PKWirnbajKyLhlXWBOi2x7uqsRYiEeFzau1rq8OQJ894uYzOAsl6BNlwoSoK/vRKfk6Xx0y8Dx1S5Px3eVObSb8uRjroRKiK1y5WECCY4cR4mDWKMDsld3UIfP6+Cg7rhuQkd0mUMQuJh2JQ2jNDFNSruaxmnSQmFpEcq8moknMqEvExTBoY+JC1pVNTZLjDkKGdhQoBxRdEs/0zgKSzb2J1z2KTwB42Sbp/HBGRGQRiiJy68rlzurspS2MysGk4SyJWsDjXfWZlLjYcmitbMTc+tuX4wHrj2VWj1XUvPu4tJY7/yCZPfKkXb876yde+l0/QuVhelow4solQqINLUumB6QaxAcRxN0cGQOIaUtlzK50UwwZMJQpC121paowKgekF7US/pL+qt6XqNnzRNjDHpknmye0jJm/NCWhSXiDMnlME6aCHRc02CmL4WYfWWESUSzkRR/Xdvw05MtG7uHLL25Zfe1jXnD45rJhHYqE6KQFbXJgVPxsD0enoyDxDhXXGnc9jjulAiJokssFbeL3HYDHCGwFQNqlL160CcOyYkQ24hUokpWEbUqpllNYptVpogVRGduE22N0pjrNlAspkOYTUvOYlJfn6J8+9pzX9w39t/wznch5rXe0SWHfr59/L+hpPeV4YX47dD4355r4ncuPjV+7ezBn93p/+JM8N53Wd8U0zH4PFeNZqJX5LpBzy4P7jXvMB80k3UWSC+EnEQw5wOPzRjrUhJTcFqV04mCtF+kGDwScyImFENiiod0VVrZmhLUat1BJuOxnSq1luLRYjxUDMWK1ZGZEywvBrEYYtx8do0dpcEIHcQ4Lc0uRtfwLbo+HR7SgU7H0ynMlLh4OfIwFRfTuaxYtRupJnddvkHhUcEFYekFVGSxMZs5MwUmp3AmHcr5hUzkqz10QKuYpRiXwpPnS/u+273qgf4FpuNxI0MlrYFMz5JNgdlDnfIvfvrsL5K+I0gVdZ5tg64F62e7Guuqixzgmn/rYley3D3ftnyxmDlbmlGeY4sx5lR2LDh09I79sTnFTsMt1e7izGRRZ3V659RHZN74cnKVjvtUVIgekW+t87Z7caNrrQsX26vsuFAICFgAK2yFfcCpeAu/md/Dc4IlIDt1O+IuxuG4oqHceQYCWmIvkovw20WAiuxFI0WhIq7mYhGMFsGiIhgqOlGEDUXeInyh6CoLgcaSaBR1WTUqMTmvBk2TiauYUKT2GnuywTVNOEZsbJ6JRpNiFPmotpzpi1b8hfzCmYUzqVCAm0xu+PDno//2xtzOxX4rlYocfgrzZ4F+cEL5kk4Qs6vXzalc7U9O9LcGZq1d5ImlvpsFEiAp3hvwWv2FmcQ4sueLQnghocialOyrnhGHyzafaMn2dX+7Z/2JLl9666kpW2qA8jEPzabWRt5W/z4/3hq1LwrjLGqMa/kEHrviBWOQTzIn4fT0lIDsEXqLdhQdLCJFc4di5yneVKw5KWg2l8+zESDS3NG5+MRcmKvIGGpoORZnWYoXC0KCrzkWvLEHY3FsrKEmQfT4phjIhiMzdNnMVIbj1GhkLMzz0tFIfSzEeJjBLI1ymNQi6kwmcizmiCFvZhqIDk7Kz0zKQz+oo4k51gIPf/fk4rseW/63pJLlpfm1ZRmql7VFnUd73vx5TqkhJTp1boavyhNPVMmVKzc5l+2sy/m3Obc2FjTHPnl43b6FKZgrnbuqJNGQOddnlNctdL10ZtxTs5gjfRpN4szFhfm1pfa7y1cPFjRwYMxrrKpvYXN/mP6UKb5Cr5xPAqMILrDdFxFJ6CriNOgSf
